### ISSUE TITLE
Event-related PAC?

### ISSUE THREAD

**Issue by choldgraf** [voytekresearch/pacpy#20]
What's the recommended way to adapt this code for event-related PAC? I assume that just running the functions on individual trials would be OK, but might run into trouble with edge artifacts, no? And moreover, what would be the best way to combine the PAC statistic across trials? You could just take the mean but that would throw out some information about the variability.

Maybe a way to deal with that is to specify a `ix_begin` parameter where it will only use indices above `ix_begin` in the pac estimation. Or maybe it'd be worth just having a trials-based function that handles this under the hood. Have you guys thought about this at all?

**Comment by hoycw** [comment]
I'm already writing something very similar to this, and after talking with Chris, the main issues/differences with the current code seem to be:

(1) making sure filtering is done on long time series (I filter on the whole time series before cutting into trials/epochs)
(2) writing the PAC calculation to deal with matrices (trials, time) instead of 1D time series

#2 begs the question, do you write new versions that are designed to handle multiple time series vs. write wrappers that do the filtering/epoching that then call only the last bits of the PAC implementation of choice. This latter version is cleaner interfacing with current code, but may get messy with some of the more complicated metrics...

Do y'all use pacpy in your event-related code, or just write similar but customized code?

**Comment by parenthetical-e** [comment]
We've been doing 1, pretty exclusively I believe. @srcole?

`pacpy` could be easily wrapped to handle 2, if desired. Just loop over rows. Might not be perfectly efficient. Trials are intrinsically short time segments, so should be fast enough? I don't think that's something we plan to do or add, but I would be glad to help y'all with it.

**Comment by choldgraf** [comment]
I think it's a good idea to have some guideline to tell people how to do the PAC estimation with a trials-based dataset, just because I imagine a lot of people will have their data in that format already. I'll probably try to include support for trials and multiple signals in the MNE PR so that we can use joblib to loop through things and make it faster. Or lemme know if you guys want that functionality in pacpy

**Comment by roemervandermeij** [comment]
Could you be more specific? :p

One thing which should be in there, which I doubt is now (based on Scott
still not doing it by default, right?), is automatic cutting off of edge
artifacts based on filter length. That data is wrong and should never be
used.

--
Roemer van der Meij
Postdoctoral Researcher
Voytek Lab
University of California, San Diego
Cognitive Science
9500 Gilman Drive
La Jolla, CA 92093-0515
E-mail: roemer.van.der.meij@gmail.com

**Comment by choldgraf** [comment]
Yeah I imagine a trials-based function as doing one of:

1. Let you pre-filter the data before you turn into trials in order to
avoid edge artifacts.
2. Let you specify start and stop indices for the PAC estimation, so that
only timepoints between those indices are used (and throw an error or
warning if people use indices that might include edge artifacts)

**Comment by srcole** [comment]
@hoycw Right, I've been imagining #1 for this situation. There is a bit of functionality built in to make this easier. 'pac.pa_series' is a function that takes input similar to PAC functions but just returns the phase time series and amplitude time series. Therefore, we can do all the filtering on the long, continuous recordings. Then, we input a subsection of these time serieses (the trial) into the main PAC function (instead of the raw data), and by setting the kwarg 'filterfn = False', we calculate PAC on this short time segment without doing the filtering.

@roemervandermeij Right. I should go ahead and implement that ASAP. I was thinking we would just need to make another function that calculates the filter length (used for filtering for the phase time series), and then chop off that filter length from each end of the signal. A few questions:
1. Should we make the edge artifact cutting a kwarg with default on or off? 
2. I think making a new filter length calculation function is cleaner than the alternative of modifying the current filtering function to return the filter length when desired, right?

**Comment by choldgraf** [comment]
You could always write some helper functions and call those (e.g.,
`_prepare_filter_signal` or something). Or make it a function that's
available to the user if it's useful enough for people to use it in custom
ways.

**Comment by roemervandermeij** [comment]
> @roemervandermeij <https://github.com/roemervandermeij> Right. I should
> go ahead and implement that ASAP. I was thinking we would just need to make
> another function that calculates the filter length (used for filtering for
> the phase time series), and then chop off that filter length from each end
> of the signal. A few questions:
> 1. Should we make the edge artifact cutting a kwarg with default on or
> off?
> 2. I think making a new filter length calculation function is cleaner than
> the alternative of modifying the current filtering function to return the
> filter length when desired, right?
>

1) No, always on. As the resulting data is directly used in PAC calculation
afterwards (right?), it should never be possible to retain the bad segments.
2) I'd say:
- Make it impossible to ever use IIR filtering for PAC calculation. Almost
everybody that uses IIR doesn't know those properties of the filter
relevant for spectral analysis (i.e. time-domain length and the associated
frequency resolution)
- Since FIR is the only possible option, simply always cut off the
filter-length on each side of the data that was filtered (before the
Hilbert transform!). When two-pass filtering, when one-pass filtering use
half the filter length.
*(Note: this is from the perspective that the filtered time-series is
indexed such that t=x in the output reflects t=x in the input multiplied
with the filter centered at t=x)*



-- 
Roemer van der Meij
Postdoctoral Researcher
Voytek Lab
University of California, San Diego
Cognitive Science
9500 Gilman Drive
La Jolla, CA 92093-0515
E-mail: roemer.van.der.meij@gmail.com

**Comment by hoycw** [comment]
This all sounds good. @srcole , did I interpret that correctly that your in house code is using this toolbox by filtering with pac.pa_series then looping over rows? Or do you just write your own custom event-related code? Either should be fine, I'm just curious to compare to what I've been doing (obviously custom code, since I didn't start looking at pacpy until this weekend).

**Comment by srcole** [comment]
Cool. I'll make an implementation for removing filter artifact in the next couple weeks.

@hoycw Right, we do the filtering and Hilbert transform on the pre-epoched data, and then calculate PAC using the epoched phase and amplitude time serieses.

So do you guys think pacpy needs anything more for doing event-related PAC. I think the setup we have now is sufficient.

**Comment by srcole** [comment]
removal of edge artifacts implemented in the branch 'edgeart.'
I just need to rewrite the unit tests.

Basically, the functions have been updated to find the # of cycles used in the filter (`filter_kwargs['w']` or `pacpy.filt.firf` default) and then call a function (`pacpy.filt.rmvedgeart`) to remove the filter length from each side of the signal. Let me know if you guys think it should be done any other way. Otherwise, we'll push it to master once the travisci problem is fixed (see issue #24)

**Comment by choldgraf** [comment]
That sounds like a reasonable approach to me - this should be documented so people know it'll happen.

**Comment by roemervandermeij** [comment]
Sounds good! 

BTW, this should also be done for the Morlet implementation (in that case only half of the filter(wavelet) length)

**Comment by srcole** [comment]
what's the status of this issue? We could:
1) Make a note in the readme about how to use this package to do trial-based PAC calculation (use filterfn=False and do some loops)
2) Write a function that takes as input the regular inputs to PAC functions + the pac method desired + a 2-column list of start and end indices for each trial.

I'm partial to (2) because it should be fairly straightforward, yeah? Or do you guys have other thoughts?

**Comment by choldgraf** [comment]
Another options would be to let it accept an extra dimension, which is
assumed to be trials. Then people could do the start/stop slicing on their
own, and then put that into the function. I assume a lot of people have
their data already in a signals x trials x time format.

**Comment by parenthetical-e** [comment]
> Another options would be to let it accept an extra dimension, which is
assumed to be trials. 

I view `pacpy` as base library. It tries to do as little as possible. As such, I am set against letting the pacpy routines accept anything but 1d arrays. I wanted simplicity and transparency in implementation, and I think we've got that. Adding an extra dimension (about which we assume things) is quite to that goal.  

I'm for 1. A good demo or option 1.5, creating a `trials` function which accepts a matrix (of trials) along with an `axis` arg, and a `pacpy` function. This 1.5 approach is consistent with the 'functional' approach takes to extending its capabilities.

**Comment by choldgraf** [comment]
I think that's a fair point. Things like MNE can build trials functionality
if need be, so long as the documentation / examples are there on pacpy's
end ;)

**Comment by srcole** [comment]
> Another options would be to let it accept an extra dimension, which is
assumed to be trials. 

But if this were the case, then we would be removing edge artifacts from each trial, which would lose a lot of data. In order to avoid this, either the user needs to do the filtering and Hilbert transform themselves on the raw data before the epoch and then use the flag `filterfn = False`, or we apply something like option 2 from my previous comment.

Sorry I just processed what you said, very delayed.

**Comment by choldgraf** [comment]
yeah agreed - and the pac metric does become a bit unstable when you do that. It wouldn't be difficult to write a function that says "give me 2 1-d arrays and an idea of when trials are, and I will do the filtering first, then split the data and return a list of PACs".

To make things simpler, rather than allowing a 2d list of trial start/stop indices, you could just ask for a single integer of trial onset indices, and then let people give "tmin" and "tmax" along with the sampling frequency, and that would be used to pull a window around each event index. That way the slicing would be guaranteed to be a square

If you guys think that's too much extra functionality for pacpy then I will implement it in MNE, but it seems to me that it's a pretty common use case

**Comment by choldgraf** [comment]
Hey all - just FYI the PR I mentioned above has been moved to MNE-sandbox because it's still in "beta" so to speak. Check it out here:

https://github.com/mne-tools/mne-sandbox/pull/7

The way I'm implementing it allows users to give indices for where their events start. Then it does the filtering etc first, and subsequently chunks up into trials. I'm closing this because it sounds like the development is more appropriate in MNE than in pacpy. LMKWYT.
