### ISSUE TITLE
PAC sensitive to signal amplitude?

### ISSUE THREAD

**Issue by choldgraf** [voytekresearch/pacpy#43]
I've been comparing PAC across data we've got from different sites, and am finding some inconsistencies between the PAC methods. In particular, I'm getting different results for some methods depending on whether or not my data has low power (across all frequencies).

I noticed that for sites with such a broadband decrease in power (for all channels, for all times), then the PAC value will be nearly identical between pairs of electrodes, so long as the phase electrode is the same. Almost like the amplitude component of PAC has almost no effect on the PAC value.

I'm guessing that this is because of the lower power in general of the amplitude signal. However, if I run the same code using another method (e.g., 'glm' or 'mi_canolty', then the PAC values are no longer identical. Additionally, if I use the same PAC method, but first normalize channels somehow (e.g., divide each channel by its mean across all times), then I also no longer get spurious identical PAC values. So a couple questions:

1. Do you expect data to be normalized in some way before running the PAC code? E.g., each channel divided by its mean across all times or something?
2. Alternatively, is it known that certain PAC metrics are sensitive to overall signal power? Any "best practices" there?
3. More generally, how do you deal with the issue of different recording sites having different levels of base power?

**Comment by parenthetical-e** [comment]
> • Do you expect data to be normalized in some way before running the PAC code? E.g., each channel divided by its mean across all times or something?

	Nope. See below.

> • Alternatively, is it known that certain PAC metrics are sensitive to overall signal power? Any "best practices" there?

	No best. Some metrics are sensitive. Some are not. We’ve taken to favoring the amplitude insensitive flavor, `ozkurt` specifically. Don’t take this to mean we don’t think amplitude matters. It can/does physiologically. Taking that into account makes for a complicated metric.

> • More generally, how do you deal with the issue of different recording sites having different levels of base power?

	There is no general answer. It’s conditional. What you are trying to accomplish?

**Comment by choldgraf** [comment]
Well basically I'm just trying to calculate PAC between electrodes, but some subjects have much lower power in general. When I use metrics like 'plv' on my low-power subjects, then all of the PAC values were the same when using the same electrode for phase.

I've switched to using 'glm' because that seems like it'd be more insensitive to amplitude since you're fitting a model (and the PAC values do differ when using this metric).

I should note that even though the subject signal has low power, it still has "normal" looking traces in high-gamma (e.g., clear auditory evoked HG increases)

**Comment by parenthetical-e** [comment]
Do you think the power differences embody something important? 

If yes, then use a sensitive metric. An example of ‘yes, it matters' might be an intra-electrode analysis looking at differences between experimental conditions. Power could be something you’d want your metric to "see".

If not, use Ozkurt (a.k.a normalized PLV). ’Not' will be the case for most inter-electrode analyses, I should think anyway.

**Comment by choldgraf** [comment]
No not really, I think it's probably something to do with the amplifiers that the sites are using...ok, sounds like Ozkurt is the way to go. Thanks. Not sure if you guys are planning on any documentation, but that'd be a good example to throw in.

**Comment by srcole** [comment]
The docstring of the comodulogram function references the papers from which these metrics were all taken. Specifically:
        'mi_tort' - See Tort, 2008
        'plv' - See Penny, 2008
        'glm' - See Penny, 2008
        'mi_canolty' - See Canolty, 2006
        'ozkurt' - See Ozkurt & Schnitzler, 2011

Honestly, I should put these references in the docstrings of the main functions too, and maybe also in the README. I'd also recommend [Tort, 2010](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2941206/) in regards to this specific issue, as it compares the sensitivities of most of these metrics. I believe he specifically addresses amplitude specificity in one figure.

> If not, use Ozkurt (a.k.a normalized PLV).
Ozkurt is very different from PLV. It could be considered normalized Canolty Modulation Index, in that it's normalized by power instead of by bootstrapping. PLV uses a very different signal when it filters the high-band amplitude envelope.

Other than that, I agree with what Erik said. Do Ozkurt, but still see how the power of your signal biases that metric. There may be some weird interaction, that I'd definitely be interested to hear about if you look into it (:

And your documentation suggestion is definitely a good one. Formally comparing PAC methods in a complementary way to Tort, 2010 was one of the initial motivations for this toolbox. It's definitely not clear which metric to use in which situation, and what variation in each metric tells you about the underlying signal. Based on your issue, and what we were also thinking, the field would benefit from a guide, in addition to Tort, 2010. We have just gotten caught up in a whole new aspect of PAC, coming to bioRxiv, hopefully soon-ish ;) But a glimpse at what we were thinking for comparing PAC metrics is in the bottom figure of our [example ipynb](https://github.com/voytekresearch/pacpy/blob/master/pacpy/examples/pacpy%20demo.ipynb). As we change one dimension of the simulation, you can see that each PAC method behaves differently (e.g. linear, exponential, saturates).

**Comment by choldgraf** [comment]
I think it's a good idea to include references w/ the docstrings for individual functions. See here for an example of how MNE handles this:

https://github.com/mne-tools/mne-python/blob/1b60b1a8d4e9bb12b2961c545aa85dd75460f129/mne/decoding/ems.py#L24

+1 for writing a nice guide on these methods...I think that people generally look towards packages for examples of "best practices" in using the code. I really like the notebook that you linked to, though it could be cleaned up a little bit. I've been trying to make something along those lines for encoding models, e.g.:

https://github.com/choldgraf/write-ups/blob/master/neuro/ecog/Encoding%20Models.ipynb

Maybe I can help flesh out your tutorials a bit, since it'd probably be good to have a pair of eyes that isn't already super comfortable with PAC methods...

**Comment by parenthetical-e** [comment]
References before params?  Hmmm.

We accept your eyes, Chris. Thank you!

**Comment by choldgraf** [comment]
Haha, of course my random selection example of an MNE docstring is one that doesn't conform to the MNE docstring conventions. They're actually usually structured like this one:

https://github.com/mne-tools/mne-python/blob/master/mne/time_frequency/_stockwell.py#L96

Maybe I should have someone peer-review my github comments before sending them out :P

**Comment by choldgraf** [comment]
I'm going to close this since I don't think there's really an "answer" here. Thanks for the tips though, much appreciated!
